openapi: 3.0.0

info:
  title: Swaagger API for clienti
  description: spec definitions for clienti
  version: 0.0.1

servers:
  - url: http://localhost:3000
    description: Local server

paths:
  /user/{id}:
    get:
      summary: Returns info of user by id.
      description: user info by id
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  idUser:
                    type: number
                  name:
                    type: string
                  lastName:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
                  address:
                    type: string
    post:
      summary: create user
      description: create user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: success saved
