openapi: 3.0.0

info:
  title: Swaagger API for clienti
  description: spec definitions for clienti
  version: 0.0.1

servers:
  - url: http://localhost:3000/api
    description: Local server
  - url: https://dev-moneyback.azurewebsites.net/api
    description: dev server
paths:
  /user/{id}:
    get:
      summary: Returns info of user by id.
      description: user info by id
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  idUser:
                    type: number
                  name:
                    type: string
                  lastName:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
                  address:
                    type: string
    post:
      summary: create user
      description: create user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: success saved
  /user:
    get:
      summary: get users
      description: get all users
      responses:
        '200':
          description: getting all users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: number
                    name:
                      type: string
                    lastName:
                      type: string
                    email:
                      type: string
                    phone:
                      type: string
                    address:
                      type: string
  /login:
    post:
      summary: login app
      description: login app
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nick:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: sucessfully loged
        '403':
          description: wrong username or password
  /cases:
    post:
      tags:
        - cases
      summary: post client app
      description: call this endpoint to save client info
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                enterprise:
                  type: string
                amountLost:
                  type: number
                moneyType:
                  type: string
                depositType:
                  type: string
                dateDeposit:
                  type: string
      responses:
        '200':
          description: succesfully saved
        '403':
          description: wrong params
    get:
      tags:
        - cases
      description: get all 
      responses:
        '200':
          description: all cases
  /file:
    post:
      tags:
        - file
      summary: post to save file
      description: save file that belongs to a case
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                caseId:
                  type: number
                fileName:
                  type: string
                fileData:
                  type: string
  /file/{caseId}:
    get:
      tags:
        - file
      summary: get files from case Id
      description: get all files saved on one caseId
      parameters:
        - in: path
          name: caseId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: all files
